### ISSUE TITLE
Rename the Operator

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/operator-certification-operator#104]
## Is your feature request related to a problem? Please describe.

The current name for the operator, **Operator Certification Operator**, feels a bit redundant and doesn't exactly roll off the tongue. In addition, the length of the name has caused problems with several child resource names being too long and resulting in those resources not being created without a workaround. Several community members have expressed frustration with the name and would like it changed.

## Describe the solution you'd like.

Ideally, this should be done before the operator begins to see use by partners. 

I propose the following candidates for renaming the operator, in the order presented, but I would love alternatives to these as well.

1. Certification Operator
2. OpenShift Certification Operator
3. Red Hat Certification Operator

## Describe alternatives you've considered.

Open to alternatives, as each candidate in the list above has an issue of some sort. For example, `Certification Operator` could be a bit too vague and the other two do not really solve the length problem, although that has already been solved in the code, so is not a major concern.
 
## Additional context.

Naming software projects is strangely one of the hardest parts of creating good software.

**Comment by bcrochet** [comment]
1. Probably not quite descriptive enough? Certification of what?
2. A little more descriptive, but still not quite there.
3. See 2.

What about:

1. Certification PIpeline Operator
2. Partner Certification Operator
3. Partner Pipeline Operator

**Comment by jomkz** [comment]
I do like Partner in the name, since Red Hat partners are the only ones who can actually use this thing. :)

**Comment by acmenezes** [comment]
I like number Brad's 2. Just thinking that partner certification may be something bigger than this operator actually does.

**Comment by jomkz** [comment]
After further discussions on this topic, we will keep the GitHub project name for this operator. The difference in naming may come when an official Red Hat product name has been chosen and we can update the relevant artifacts to reflect that but the project name will remain the same as it is now.
