### ISSUE TITLE
Conditionally Apply Various Pipelines via the CR

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-certification-operator#105]
## Is your feature request related to a problem? Please describe.
Right now we are applying all of the pipelines `ci/hosted/release` this could be confusing to partners since they only care about the `ci` pipeline.

## Describe the solution you'd like.
Update the CRD to have a boolean for for each for each pipeline type, something like the below.

- `applyCiPipeline: true` - true by default in our sample
- `applyHostedPipeline: false` false by default in our sample
- `applyReleasePipeline: false` false by default in our sample

Based on what the user provides when they apply the CR, we would only apply the  tekton `Pipeline`resource(s) that the user requested. To keep things simple for the operator we can still apply all the tasks so we do not have to worry about looking in the pipeline `yaml` files to distinguish which task(s) goes with which pipeline(s).

We would then check for these booleans in the `applyManifests` code found [here](https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/main/controllers/dependencies.go#L110).

## Describe alternatives you've considered.
Open to other ideas, but these are my initial thoughts.

## Additional context.
N/A

**Comment by itroyano** [comment]
The list of pipelines and/or their names can change in the future,  so we can instead of `boolean` have an `enum`?
