### ISSUE TITLE
Add in the Ability for the Operator to Update OperatorPipelineStatus

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-certification-operator#22]
## Is your feature request related to a problem? Please describe.
Currently the operator only logs errors, and unless a cluster admin is tailing the controller manager logs, the `OperatorPipelineStatus`  isn't reflected properly in the `OperatorPipeline` CR. 

## Describe the solution you'd like.
It would be great if the operator could implement OperatorPipelineStatus for any information (secrets/kubeconfigs/etc) that the cluster admin has not provided, so `OperatorPipeline` status is clearly defined.

## Describe alternatives you've considered.
N/A

## Additional context.
N/A

**Comment by itroyano** [comment]
just a quick +1 on this.
