### ISSUE TITLE
Document usage steps into readme.md

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/operator-certification-operator#29]
Also consider creating a dev doc for contributors,  similar to how it's done in Preflight.

**Comment by dcurran90** [comment]
main Readme.md in top level of repo should include something along the lines of:

Pre-installation:
   Before you start section include from current docs
  steps 1, 4, 7 included from current docs

Installation:
  add catalog source and install bundle (needs to be written)

Usage:
  how to run pipeline included from current docs

**Comment by acornett21** [comment]
Here is the original document
https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/ci-pipeline.md#operator-certification-ci-pipelineinstructions
