### ISSUE TITLE
Suppress `already-exists` exception for `operator-ci-pipeline`

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-certification-operator#31]
## Bug Description
When reconcile happens for a 2nd time the below error happens and causes the operator to not reconcile further.

```
2021-11-11T10:15:14.370-0700    ERROR   controller_operatorpipeline     Couldn't iterate over operator-pipelines yaml manifest files    {"error": "pipelines.tekton.dev \"operator-ci-pipeline\" already exists"}
```

## Version and Command Invocation
sha of code under test `b587f2a87e0328c1d910c9cc3fa685c984d76590`

## Steps to Reproduce:

1) Run the application
2) wait for the reconcile to happy for a second time and see failure

## Expected Result
I expect that this operator suppress `already exists` exceptions to not output to the logs/console.

## Actual Result
This error is logged and throw back up the stack, thus stopping the reconciliation process

## Additional Context
N/A

**Comment by dcurran90** [comment]
also seeing a problem that when the OperatorPipeline CR is deleted the pipelines do not get cleaned up. I don't believe the correct ownership is set up.
I'm thinking this needs to be a separate issue but wanted to bring it up here as it's sort of related

**Comment by acornett21** [comment]
@dcurran90 I noticed that too and I was not sure if the operator should `own` any resources. But if it were to own resources, the `pipeline` would be one I could see as potentially owning. Good, to call out.
