### ISSUE TITLE
Resources created by the operator do not get cleaned up when CR is deleted

### ISSUE THREAD

**Issue by dcurran90** [redhat-openshift-ecosystem/operator-certification-operator#40]
## Bug Description

The operator creates various resources (pipelines, subscriptions) but not all of them are owned by the custom resource and end up not getting removed when the OperatorPipeline CR is deleted

## Steps to Reproduce:

1) Created OperatorPipeline CR `oc apply -f config/samples/certification_v1alpha1_operatorpipeline.yaml`
2) Wait for operator to resolve
3) Delete OperatorPipeline CR `oc delete -f config/samples/certification_v1alpha1_operatorpipeline.yaml`
4) View pipelines (or any other created resources) in the UI and see that they still exist

## Expected Result

All resources directly created by the operator get removed 

## Actual Result

Some resources (pipelines specifically) stick around

## Additional Context

Mostly has to do with ownership of the new resources not being set to the OperatorPipeline resource. This will likely not be a standard case because we run yaml from another repo to create most (if not all) of the resources in question.
https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/main/controllers/dependencies.go#L24-L76

**Comment by acmenezes** [comment]
Hi Dan, I got this problem too here. Checking this one out.
PR for that in the oven.

/assign
