### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by dcurran90** [redhat-openshift-ecosystem/operator-certification-operator#41]
Add docs directory for developer documentation and start a developer readme.
We stick pretty closely to the standard operator-sdk practices right now but it should still be useful to have included especially if/when things start to diverge

**Comment by acornett21** [comment]
#107

**Comment by jomkz** [comment]
Going to close this for now, as this was addressed by #107. We can add further issues as needed to expand on what we have now.
