### ISSUE TITLE
Update CSV with real information

### ISSUE THREAD

**Issue by dcurran90** [redhat-openshift-ecosystem/operator-certification-operator#43]
## Is your feature request related to a problem? Please describe.

We definitely need an appropriate icon and description. 

## Describe the solution you'd like.

We do not have the icon or description at the moment so part of this effort will be to lock them down.
The preflight run may also provide more required updates so watch those results if they are available or we can just create new issues when those results become available.

**Comment by dcurran90** [comment]
From @itroyano 

most changes go into https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob[…]ases/operator-certification-operator.clusterserviceversion.yaml
there’s an icon section where we’d put the base64 encoded icon.
and there’s the description, displayName, maintainers, links we’d like to enhance.

style changes can be tested during development, by pasting the file into https://operatorhub.io/preview.

also it’s possible to locally untar and look at the generated CSV with all the Roles and Deployment -
docker pull https://quay.io/repository/opdev/operator-certification-operator-bundle:353ed1914adfe4d20c73fece8afbdd3de239b079
docker images --> get image id
docker save <image_id> -o bundle.tar && tar -xf bundle.tar  --> untar the layer and open up CSV.

**Comment by dcurran90** [comment]
also, plan is to support 4.8 and 4.9
https://access.redhat.com/support/policy/updates/openshift#dates

**Comment by itroyano** [comment]
csv code links are broken....

anyways it's

/config/manifests/bases/operator-certification-operator.clusterserviceversion.yaml

and

/bundle/manifests/operator-certification-operator.clusterserviceversion.yaml

**Comment by acornett21** [comment]
This may or may not make sense, but below is a link I just submitted to community operators, that has a checklist for some of the things in needed in the CSV. Let me know if this is helpful or makes sense.

https://github.com/k8s-operatorhub/community-operators/pull/404
