### ISSUE TITLE
Deploy the operator certification pipeline resources

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/operator-certification-operator#5]
The operator needs to deploy the operator certification pipeline resources inline with the instructions in step 6 from the Operator Certification CI Pipeline Instructions document.

https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/ci-pipeline.md#step6

**Comment by acmenezes** [comment]
PR #13 for this just got out of the oven.
