### ISSUE TITLE
Add support for digest pinning

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/operator-certification-operator#6]
The operator should support digest pinning as documented in the Operator Certification CI Pipeline Instructions.

https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/ci-pipeline.md#digest-pinning-config

**Comment by acornett21** [comment]
Key to be used in CR should be `github-ssh-credentials` when creating the secrete, since this is the value the pipeline uses.
