### ISSUE TITLE
Add Openshift-Pipelines as a certification-operator dependency

### ISSUE THREAD

**Issue by acmenezes** [redhat-openshift-ecosystem/operator-certification-operator#69]
## Is your feature request related to a problem? Please describe.

Yes. Operator fails in the absence of the tekton CRDs or when openshift-pipelines are not ready.

## Describe the solution you'd like.

Register the openshift-pipelines operator as a dependency for certification operator.

## Describe alternatives you've considered.

We've considered creating the subscription to openshift-pipelines directly from the certification operator itself but it doesn't build the controller when owning the tekton resources since it doesn't have the CRD in the cluster yet.

## Additional context.

Test were made in brand new clusters and it breaks as it is if the openshift-pipelines is not installed.

Linked issues describing it are #58 and #59

**Comment by acornett21** [comment]
#90
