### ISSUE TITLE
Allow usage of GitHub API Token for results submission

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/operator-certification-operator#8]
The operator should allow the user to provide a secret containing a GitHub API Token for results submission as documented in the Operator Certification CI Pipeline Instructions.

https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/ci-pipeline.md#add-a-github-api-token-for-the-repo-where-the-pr-will-be-created

**Comment by acornett21** [comment]
Key to be used in CR should be `github-api-token` when creating the secrete, since this is the value the pipeline uses.
