### ISSUE TITLE
Add operator-sdk install to Makefile

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-certification-operator#80]
## Is your feature request related to a problem? Please describe.
Since every developer working on this operator could potentially have a different version of `operator-sdk` installed locally, when `make bundle` is run, a new version of the SDK is listed in various artifacts. This makes reviews, problematic, but could also cause unintended issues if someone has an extremely old version of the SDK.

## Describe the solution you'd like.
Pull down the SDK like other binaries, ie `controller-gen`. The only issue I see with this approach is that the binaries in the `/bin` folder in the app do not have a `version` on them when running `controller-gen version` since go is pulling  and building them manually. Im not sure the right approach to make sure we get a version on the `operator-sdk` binary.

Logs for context.
```shell
╭─acornett at acornett-mac in ~/go/src/github.com/acornett21/operator-certification-operator on set_condition_pryxis_secret✘✘✘
╰─± ./bin/operator-sdk version
operator-sdk version: "unknown", commit: "unknown", kubernetes version: "unknown", go version: "go1.17.3", GOOS: "darwin", GOARCH: "amd64"
╭─acornett at acornett-mac in ~/go/src/github.com/acornett21/operator-certification-operator on set_condition_pryxis_secret✘✘✘
╰─± ./bin/kustomize version
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin GoArch:amd64}
```

## Describe alternatives you've considered.
N/A

## Additional context.
Below is some quick changes I put together, but like mentioned above, this approach leads to generation with a `version` appearing as `unknown`

```shell
OPERATOR_SDK = $(shell pwd)/bin/operator-sdk
operator-sdk: ## Download operator-sdk locally if necessary.
	$(call go-get-tool,$(OPERATOR_SDK),github.com/operator-framework/operator-sdk/cmd/operator-sdk@v1.15.0)
	
bundle: operator-sdk manifests kustomize ## Generate bundle manifests and metadata, then validate generated files.
	./bin/operator-sdk generate kustomize manifests -q
	cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
	$(KUSTOMIZE) build config/manifests | ./bin/operator-sdk generate bundle -q --overwrite --version $(RELEASE_TAG) $(BUNDLE_METADATA_OPTS)
	./bin/operator-sdk bundle validate ./bundle
```

**Comment by itroyano** [comment]
@acornett21 consider the downstream version of sdk, rather than the original/upstream.

**Comment by acornett21** [comment]
@itroyano Are you suggesting https://github.com/openshift/ocp-release-operator-sdk? To my knowledge no one on the team uses this and this lags way behind the upstream.
