### ISSUE TITLE
Allow usage of a Red Hat Container API access key for results submission

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/operator-certification-operator#9]
The operator should allow the user to provide a secret containing a Red Hat Container API access key for results submission as documented in the Operator Certification CI Pipeline Instructions.

https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/ci-pipeline.md#add-red-hat-container-api-access-key

**Comment by acornett21** [comment]
Key to be used in CR should be `pyxis-api-secret` when creating the secrete, since this is the value the pipeline uses.

**Comment by bcrochet** [comment]
Fixed by #23
