### ISSUE TITLE
update readme/install docs and csv to be more accurate

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/operator-certification-operator#93]
### What is the URL of the document?
Readme and /doc/installation

### Which section(s) is the issue in?
We no longer need to reference the installation of the pipelines operator anywhere in our docs

### What needs fixing?
Remove unneeded section(s)

#### Additional context
We also might want to think of how to say 'we can watch any NS that our CR is created in' so things are more clear for a user where to put the secrets.

**Comment by jomkz** [comment]
@acornett21 Can this issue be closed?

**Comment by acornett21** [comment]
#106
